## Introduction 

It forms the foundation of the python scientifc computing stack and is used for a variety of purposes like:
- Linear Algebra
- Image Processing
- Signal Processing etc.

A lot of popular & widely used libraries like Pandas, Matplotlib, OpenCV, scikit-learn are based in NumPy.


## NumPy Topics
1. Basics - Defining an array, checking it's shape & dimensions, reshaping an array, np.zeros, np.ones, np.random numbers & integers, converting datatypes. <br>
2. Subsetting an array using indexes and boolean conditions <br>
3. Element wise maths on np arrays <br>
4. Matrix operations in numpy <br>

In [1]:
## Loading required modules

import numpy as np

### NumPy Basics

In [2]:
## Defining an array

# 1D array
a1 = np.array([1,2,3])

## 2D array
a2 = np.array([[1,2],[3,4]])

## 3D array
a3 = np.array([[[1,2],[3,4]]])

In [3]:
## Checking the dimensions of defined arrays

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [4]:
## Checking the shape of defined arrays

print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 2)
(1, 2, 2)


In [5]:
## Reshaping an array

a3.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [6]:
## Defining an array of all zeros

print(np.zeros(a2.shape))
print('\n')
print(np.zeros_like(a2))

[[0. 0.]
 [0. 0.]]


[[0 0]
 [0 0]]


In [7]:
## Defining an array of all ones

print(np.ones(a2.shape))
print('\n')
print(np.ones_like(a2))

[[1. 1.]
 [1. 1.]]


[[1 1]
 [1 1]]


In [8]:
## Defining an array of random numbers

print(np.random.rand(2,2))
print('\n')
print(np.random.random_sample(a2.shape))

[[0.83830517 0.18474723]
 [0.97789634 0.80655445]]


[[0.78337667 0.23786547]
 [0.8088359  0.67932701]]


In [9]:
## Defining an array of random integers

print(np.random.randint(4,size = (2,2)))

[[1 3]
 [3 3]]


In [10]:
## Converting datatypes

print(a2.dtype)
print('\n')
a2 = a2.astype('float32')
print(a2)
print('\n')
print(a2.dtype)

int64


[[1. 2.]
 [3. 4.]]


float32


### Stacking Arrays 

In [11]:
## Vertical stacking

a1 = np.array([1,2,3])
s = np.array([1,2,3])

np.vstack((a1,s))

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
## Horizontal stacking

a1 = np.array([1,2,3])  
s = np.array([1,2,3])

np.hstack((a1,s))

array([1, 2, 3, 1, 2, 3])

### Subsetting an array

In [13]:
## Subsetting a 1D array
print(a1)

# Single element
print(a1[1])

# Multiple elements
print(a1[[1,2]])

[1 2 3]
2
[2 3]


In [14]:
## Subsetting a 3D array

print(a3)
print('\n')

# Single element
print(a3[0,0,1])

print('\n')

# Multiple elements
print(a3[0,[0,1],[1,1]])

[[[1 2]
  [3 4]]]


2


[2 4]


In [15]:
## Using boolean conditions
print(a2)
print('\n')

print(a2>2)
print('\n')

print(a2[a2 > 2])

print('\n')
print(a2[a2 == 2])

[[1. 2.]
 [3. 4.]]


[[False False]
 [ True  True]]


[3. 4.]


[2.]


In [16]:
## Replacing a value in an array

a1 = np.array([1,2,3])
print(a1)

a1[1] = 100

print('\n')
print(a1)

[1 2 3]


[  1 100   3]


### Element-wise math operations

In [17]:
a1 = np.array([1,2,3])
print(a1)

print('\n')
print(a1*2)

print('\n')
print(a1 + 10)

print('\n')
print(a1 - 10)

print('\n')
print(a1/10)

[1 2 3]


[2 4 6]


[11 12 13]


[-9 -8 -7]


[0.1 0.2 0.3]


In [18]:
a1 = np.array([1,2,3])
print(a1)

print('\n')
print(a1 + a1)

print('\n')
print(a1 * a1)

[1 2 3]


[2 4 6]


[1 4 9]


In [19]:
a2 = np.array([[1,2],[3,4]])
print(a2)

print('\n')
print(a2 + a2)

print('\n')
print(a2 * a2)

[[1 2]
 [3 4]]


[[2 4]
 [6 8]]


[[ 1  4]
 [ 9 16]]


### Matrix Operations

In [20]:
m1 = np.ones((3,2))
m2 = np.array([[3,3],[4,4]])

## Matrix Multiplication
print(np.matmul(m1,m2))
print('\n')
print(np.dot(m1,m2))

## Matrix Transpose
print('\n')
print(m1.T)

## Inverse
print('\n')
a = [[1,2],[5,6]] ## example taken from geekforgeeks
print(np.linalg.inv(a))
print(np.dot(np.linalg.inv(a), a)) ## checking if inverse is correct or not

## Identity matrix
print('\n')
print(np.identity(2))

## row-wise summation
print('\n')
print(np.sum(m1, axis=1))

## column-wise summation
print('\n')
print(np.sum(m1, axis=0))


## There are other operations like max, min, mean etc. as well that can be performed on matrices

[[7. 7.]
 [7. 7.]
 [7. 7.]]


[[7. 7.]
 [7. 7.]
 [7. 7.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[-1.5   0.5 ]
 [ 1.25 -0.25]]
[[ 1.00000000e+00  8.88178420e-16]
 [-2.22044605e-16  1.00000000e+00]]


[[1. 0.]
 [0. 1.]]


[2. 2. 2.]


[3. 3.]
